# Generated by Django 3.0.8 on 2020-08-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20200803_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='tag',
            field=models.ManyToManyField(to='gallery.Tag'),
        ),
    ]
