# Generated by Django 3.0.8 on 2020-08-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20200803_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='tag',
            field=models.ManyToManyField(to='gallery.Tag'),
        ),
    ]
