# Generated by Django 3.0.8 on 2020-08-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_auto_20200804_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='tag',
        ),
    ]
